openapi: 3.0.0
info:
  title: API de Gestão de Tarefas
  description: Documentação da API de Gestão de Tarefas
  version: 1.0.0

paths:
  /tarefas:
    get:
      summary: Listar todas as tarefas
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              example:
                - id: 1
                  title: "Concluir Projeto"
                  description: "Finalizar o trabalho prático de API de Gestão de Tarefas"
                  due_date: "2023-11-30"
                  priority: "Alta"
                  status: "Pendente"

    post:
      summary: Criar uma nova tarefa
      requestBody:
        required: true
        content:
          application/json:
            example:
              title: "Nova Tarefa"
              description: "Descrição da nova tarefa"
              due_date: "2023-12-01"
              priority: "Média"
              status: "Pendente"
      responses:
        '201':
          description: Tarefa criada com sucesso
          content:
            application/json:
              example:
                id: 2
                title: "Nova Tarefa"
                description: "Descrição da nova tarefa"
                due_date: "2023-12-01"
                priority: "Média"
                status: "Pendente"

  /tarefas/{id}:
    get:
      summary: Obter detalhes de uma tarefa específica
      parameters:
        - name: id
          in: path
          required: true
          description: ID da tarefa
          schema:
            type: integer
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              example:
                id: 1
                title: "Concluir Projeto"
                description: "Finalizar o trabalho prático de API de Gestão de Tarefas"
                due_date: "2023-11-30"
                priority: "Alta"
                status: "Pendente"

    put:
      summary: Atualizar uma tarefa existente
      parameters:
        - name: id
          in: path
          required: true
          description: ID da tarefa
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            example:
              title: "Tarefa Atualizada"
              description: "Nova descrição da tarefa"
              due_date: "2023-12-02"
              priority: "Alta"
              status: "Em Progresso"
      responses:
        '200':
          description: Tarefa atualizada com sucesso
          content:
            application/json:
              example:
                id: 1
                title: "Tarefa Atualizada"
                description: "Nova descrição da tarefa"
                due_date: "2023-12-02"
                priority: "Alta"
                status: "Em Progresso"

    delete:
      summary: Apagar uma tarefa existente
      parameters:
        - name: id
          in: path
          required: true
          description: ID da tarefa
          schema:
            type: integer
      responses:
        '204':
          description: Tarefa apagada com sucesso

# Adicione mais paths conforme necessário para outros endpoints

